<?php

CONST RESOURCES_DIR = __DIR__ .'/resources/';

CONST INPUT_FILE = RESOURCES_DIR. 'forSort.txt';
CONST RESULT_FILE = RESOURCES_DIR .'result.txt';
CONST FIRST_TEMP_FILE = RESOURCES_DIR .'b.txt';
CONST SECOND_TEMP_FILE = RESOURCES_DIR . 'c.txt';
